spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: postgres
    password: thienphu123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
server:
  error:
    include-message: always
